### ISSUE TITLE
Add pywinauto action

### ISSUE THREAD

**Issue by Tapeline** [Tapeline/Embark#4]
### Description

Add a pywinauto action that can launch a command an then do some pywinauto automation. We can implement our own simplistic language or just interpret python code using pywinauto library:

```yml
std.winauto:
  launch: my-wizard.exe
  steps:
  - wait-window "Setup Wizard"
  - click-button "Next"
  - click-button "I agree"
  - wait-button "Finish"
  - click-button "Finish" 
```

### Reasoning

Some manipulations may still require some input (via mouse or keyboard) from user. We should automate it too
